namespace MarkdownTools.Models
{
    public enum NodeType
    {
        Blockquote,
        CodeBlock,
        Heading,
        HorizontalRule,
        Image,
        InlineCode,
        Italic,
        LineBreak,
        Link,
        Newline,
        OrderedList,
        OrderedListItem,
        Paragraph,
        Root,
        Strikethrough,
        Strong,
        Table,
        TableCell,
        TableCellHead,
        TableRow,
        Text,
        UnorderedList,
        UnorderedListItem,
        Whitespace
    }
}